### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by DimCore3** [moatazeldebsy/Appium-Server-GitHub-Action#1]
@BeforeClass
    public void setUp() throws MalformedURLException {
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("automationName" , "UiAutomator1");
        caps.setCapability("platformName" , "Android");
        caps.setCapability("platformVersion" , "7.1.1");
        caps.setCapability("deviceName" , "Android Emulator");
        caps.setCapability("app" , System.getProperty("user.dir")+"/apps/selendroid-test-app-0.17.0.apk");
        driver = new AndroidDriver<>(new URL("http://localhost:4723/wd/hub"), caps);
    `}```

**Comment by moatazeldebsy** [comment]
What the type of enhancement here @DimCore3 , can you explain more?

**Comment by moatazeldebsy** [comment]
Hi, @DimCore3 if there is no suggestion will close it. Thanks
