### ISSUE TITLE
GitHub actions pipeline ERROR

### ISSUE THREAD

**Issue by YauheniPo** [moatazeldebsy/Appium-Server-GitHub-Action#4]
Could you please explain to me the reason of issue?
https://github.com/YauheniPo/py-robot-framework-mobile-testing/runs/1134673310?check_suite_focus=true#step:3:604

**Comment by moatazeldebsy** [comment]
@YauheniPo Thank you, I just changed the `Nodejs` version to be `14`, please use release version `V1.0.5`
